app/booking/forms.py
# Contributors: Aure
# we want to import wtforms to help us with the validation
from flask_wtf import FlaskForm
# we need to import all the form fields as-well
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Email


# this form is used by the renter to send a request for a property, their email is required along with some
# information in the content section, specifically, the length of time they need the property so the invoice properly
# reflects this. There are no restrictions on the length required in the content section
# wtform validation is included in the stringfield for the email
# the render_kw are there to add the placeholders for the string field type entries
# then once again the submit field is included.
class BookingRequestForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()],
                        render_kw={"placeholder": "name@email.com"}
                        )
    content = TextAreaField('Content',
                            validators=[DataRequired()])
    submit = SubmitField('send request')


# this form is where the property owner sends an invoice to the renter, the price must be an integer thus it is
# categorised as a IntegerField
# then once again the submit field is included
class SendInvoiceForm(FlaskForm):
    price = IntegerField('price',
                         validators=[DataRequired()],
                         render_kw={"placeholder": "price in pounds eg. 60"}
                         )
    submit = SubmitField('send request')

app/posts/forms.py
# Contributors: Aure, Kowther, Ariel
# we want to import wtforms to help us with the validation
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
# we need to import all the form fields as-well
from ukpostcodeutils import validation
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError


# this allows for the postcodes to be validated to ensure they are indeed a valid UK postcode
# this is a piece of code which incorporated the use of the ukpostcodeutils dictionary
# and the function below was modified from: https://pypi.org/project/uk-postcode-utils/
def post_code_validator(form, field):
    if not validation.is_valid_postcode(field.data):
        raise ValidationError('Invalid UK Post Code')


# this is the form which allows the property owner to create a post
# all the aspects of the post form have the validation that they are a required field except for space size
#
# the location has the added validation using the fucntion above (post_code_validator) to ensure the location is a
# valid UK postcode.
# Space_size is a select field as the sizes for the posts are standardised and there are 6 options
# the pictures for posts takes the form of a filefield and it includes 2 bits of validation; that
# the picture is required and that they must have the extensions jpg or png only. finally there is a submit field to
# allow the user to post their property
class PostForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired()])
    content = TextAreaField('Content',
                            validators=[DataRequired()])
    location = StringField('Postcode', validators=[DataRequired(), post_code_validator])

    space_size = SelectField('Space Size', validators=[DataRequired()], default=('0', 'Select'),
                             choices=[('0', 'Select'), ('Extra Small', 'XS'),
                                      ('Small', 'S'), ('Medium', 'M'),
                                      ('Medium Large', 'ML'), ('Large', 'L'),
                                      ('Extra Large', 'XL')])
    picture_for_posts = FileField('Post picture',
                                  validators=[FileRequired(), FileAllowed(['jpg', 'png'])]
                                  )
    submit = SubmitField('Post')


class UpdatePostForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired()])
    content = TextAreaField('Content',
                            validators=[DataRequired()])
    location = TextAreaField('location', validators=[DataRequired()])
    space_size = SelectField('Space Size', default=('0', 'Select'), choices=[('0', 'Select'), ('Extra Small', 'XS'),
                                                                             ('Small', 'S'), ('Medium', 'M'),
                                                                             ('Medium Large', 'ML'), ('Large', 'L'),
                                                                             ('Extra Large', 'XL')])
    picture_for_posts = FileField('Post picture',
                                  validators=[FileAllowed(['jpg', 'png'])]
                                  )
    submit = SubmitField('Update')


class QuestionForm(FlaskForm):
    question = TextAreaField('ask question here',
                             validators=[DataRequired()])
    submit = SubmitField('submit question'
                         '')


class AnswerForm(FlaskForm):
    answer = TextAreaField('Content',
                           validators=[DataRequired()])
    submit = SubmitField('submit answer')

app/booking/routes.py
# Contributors: Aure Enkaoua
import stripe  # for payment
from flask import flash, redirect, url_for, render_template, request, Blueprint
from flask_login import login_required, current_user

from app import db
from app.booking.forms import BookingRequestForm, SendInvoiceForm
from app.main.routes import role_required
from app.models import Book

# for stripe booking
pub_key = 'pk_test_IzPesEUVXnPzY8a4Ecvr3J7C00bikUjRsi'
secret_key = 'sk_test_H8AjWDFHjwYjMkzloMCbE4qA00XSQyhQbS'
stripe.api_key = secret_key

# we create an instance of blueprint as main
bp_booking = Blueprint('booking', __name__)


# This is the requesting of a property by a renter. They need to fill in the required info in the
# form in order to create a row in the Book db. When this is done, they will be redirected to the
# profile, as this is where all the booking process takes place.
@bp_booking.route('/book/<postid>', methods=['GET', 'POST'])
@login_required
@role_required('renter')
def book(postid):
    form_request_booking = BookingRequestForm()
    if form_request_booking.validate_on_submit():
        content = form_request_booking.content.data
        email = form_request_booking.email.data
        book = Book(renter_user_id=current_user.get_id(), post_id=postid, content=content, email=email)
        db.session.add(book)
        db.session.commit()
        flash(
            'You have successfully posted a request for the property! You can track your booking in your profile page!',
            'success')
        return redirect(url_for('user.profile'))
    return render_template('request_booking.html', form=form_request_booking)


# This is where the PO sends teh invoice for a specific booking. When this is complete,
# we can add the price of the property, and set the status to 'payment required'.
@bp_booking.route('/send invoice/<bookid>', methods=['GET', 'POST'])
@login_required
@role_required('property_owner')
def send_invoice(bookid):
    form_send_invoice = SendInvoiceForm()
    book = Book.query.filter_by(book_id=bookid).first()

    if form_send_invoice.validate_on_submit():
        book.price = form_send_invoice.price.data
        book.status = 'payment required'
        db.session.commit()

        flash('You have successfully sent an invoice!', 'success')
        return redirect(url_for('main.home_page'))
    return render_template('send_invoice.html', form=form_send_invoice)


# This is the payment page. The renter, when he clicks on 'make payment' for a specific booking,
# it will bring them to this page, and they will make the payment specified in the invoice sent
# by the property owner.
@bp_booking.route("/booking/<bookid>", methods=['GET', 'POST'])
@login_required
@role_required('renter')
def payment(bookid):
    invoice = Book.query.with_entities(Book.book_id, Book.price).filter_by(book_id=bookid).first()
    return render_template('payment.html', pub_key=pub_key, invoice=invoice)


# Stripe checkout. We need a customer, which is our stripe account, ans our stripe token.
# To this customer, we specify how much to pay them, and we set the currency to gbp.
# We also change the status of booking to 'payed' once this is complete.
@bp_booking.route('/pay/<bookid>', methods=['POST'])
@login_required
@role_required('renter')
def pay(bookid):
    customer = stripe.Customer.create(email=request.form['stripeEmail'], source=request.form['stripeToken'])
    book = Book.query.filter_by(book_id=bookid).first()
    charge = stripe.Charge.create(
        customer=customer.id,
        amount=book.price * 100,
        currency='gbp',
        description='Space4Less renting space'
    )
    book.status = 'payed'
    db.session.commit()
    flash('you have successfully payed for the property', 'success')
    return redirect(url_for('main.home_page'))

app/posts/routes.py
# Contributors: Kowther, Aure, Ariel
import os
import secrets

from flask import current_app, request, flash, redirect, url_for, render_template, Blueprint
from flask_login import login_required, current_user

from app import db
from app.main.routes import role_required
from app.models import Post, User, Comment
from app.posts.forms import PostForm, QuestionForm, AnswerForm, UpdatePostForm

# we create an instance of blueprint as main
bp_posts = Blueprint('posts', __name__)


# this is the function created to allow for pictures that a property owner uploads as part of the post to be saved.
# this function essentially creates a hex and attaches it onto the file extension (either jpg or png) and uses an OS
# join to save the route to the picture to the database as the image itself cannot be saved the image itself is saved
# in the POST_UPLOAD route (which is configured in the config.py) which  basically means the pictures themselves are
# saved to the static/post_pictures folder. Finally the path to the image is saved to the database and the post_image
# is returned
# Modified from: https://github.com/CoreyMSchafer/code_snippets/blob/master/Python/Flask_Blog/07-User
# -Account-Profile-Pic/flaskblog/routes.py.  Date retrieved: [2020/03/05]
def saving_pictures_post(post_picture):
    hide_name = secrets.token_hex(6)
    _, f_extension = os.path.splitext(post_picture.filename)
    post_image = hide_name + f_extension
    config = current_app.config
    post_path = os.path.join(config['POST_UPLOAD'], post_image)
    post_picture.save(post_path)
    return post_image


# beginning on the form_post.picture_for_posts.data line, the picture is requested from the user
# after which the saving_pictures_post() function created above is called to save the image to
# the folder and the path to the image is saved to the database
@bp_posts.route('/post', methods=['GET', 'POST'])
@login_required
@role_required('property_owner')
def post():
    form_post = PostForm()
    if form_post.validate_on_submit():
        if form_post.picture_for_posts.data:
            file = request.files['picture_for_posts']
            pic = saving_pictures_post(file)
            form_post.picture_for_posts = pic
        post = Post(title=form_post.title.data, content=form_post.content.data,
                    image=form_post.picture_for_posts, location=form_post.location.data,
                    space_size=form_post.space_size.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('you have successfully posted your space!!', 'success')
        return redirect(url_for('main.home_page'))
    image = url_for('static', filename='post_pictures/' + str(form_post.picture_for_posts))
    return render_template('post.html', title='Post', content='content', image=image, form=form_post)


# Route to view a single post. It has comments and answers of that post aswell.
# If you are a renter, you can also submit a question in this page.
@bp_posts.route("/single_post/<post_id>", methods=['GET', 'POST'])
@login_required
def single_post(post_id):
    post = Post.query.get_or_404(post_id)
    user = User.query.get(current_user.get_id())
    form_question = QuestionForm()
    comments = Comment.query.filter_by(post_id=post_id) \
        .join(User, Comment.renter_user_id == User.user_id) \
        .add_columns(Comment.question, Comment.answer, Comment.date_posted, User.username, User.image_file,
                     Comment.comment_id) \
        .all()
    if form_question.validate_on_submit():
        comment = Comment(question=form_question.question.data, renter_user_id=user.user_id, post_id=post.post_id)

        db.session.add(comment)
        db.session.commit()
        flash('you have successfully commented on the post', 'success')
        return redirect(url_for('main.home_page'))
    return render_template('single_post.html', title=post.title, post=post, form=form_question, comments=comments)


# This is the answer route for a specific comment. Can be accessed only by a PO that owns
# that specific property.
@bp_posts.route('/answer/<commentid>', methods=['GET', 'POST'])
@login_required
@role_required('property_owner')
def answer(commentid):
    answer_form = AnswerForm()
    comment = Comment.query.filter_by(comment_id=commentid).first()
    if answer_form.validate_on_submit():
        comment.answer = answer_form.answer.data
        db.session.commit()
        flash('you have successfully posted an answer', 'success')
        return redirect(url_for('main.home_page'))
    return render_template('answer.html', form=answer_form)


# Update post route, just like update profile but for a post.
@bp_posts.route("/update_post/<postid>", methods=['GET', 'POST'])
@role_required('property_owner')
def update_post(postid):
    post_obj = Post.query.get(postid)
    form_updatePost = UpdatePostForm()
    if form_updatePost.validate_on_submit():
        if form_updatePost.picture_for_posts.data:
            file = request.files['picture_for_posts']
            pic = saving_pictures_post(file)
            post_obj.image = pic
        post_obj.title = form_updatePost.title.data
        post_obj.content = form_updatePost.content.data
        post_obj.location = form_updatePost.location.data
        post_obj.space_size = form_updatePost.space_size.data
        db.session.commit()
        flash('You have successfully updated your post!', 'success')
        return redirect(url_for('user.my_posts'))
    elif request.method == 'GET':
        form_updatePost.title.data = post_obj.title
        form_updatePost.content.data = post_obj.content
        form_updatePost.location.data = post_obj.location
        form_updatePost.space_size.data = post_obj.space_size
    return render_template('update_post.html', title='Update a post', form=form_updatePost)

app/templates/FAQ.html
<!-- Contributors: Kowther Elmi
this is a template for the FAQ page-->
{% extends 'layout.html' %}
{% block content %}
    <h3> felis eu blandit iaculis, tortor mi egestas elit?</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper venenatis magna nec tempus.
        Suspendisse congue diam quis tortor imperdiet, non pulvinar ligula venenatis.
    </p>
    <h3> felis eu blandit iaculis, tortor mi egestas elit?</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper venenatis magna nec tempus.
        Suspendisse congue diam quis tortor imperdiet, non pulvinar ligula venenatis.
    </p>
    <h3> felis eu blandit iaculis, tortor mi egestas elit?</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper venenatis magna nec tempus.
        Suspendisse congue diam quis tortor imperdiet, non pulvinar ligula venenatis.
    </p>
    <h3> felis eu blandit iaculis, tortor mi egestas elit?</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper venenatis magna nec tempus.
        Suspendisse congue diam quis tortor imperdiet, non pulvinar ligula venenatis.
    </p>
    <h3> felis eu blandit iaculis, tortor mi egestas elit?</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper venenatis magna nec tempus.
        Suspendisse congue diam quis tortor imperdiet, non pulvinar ligula venenatis.
    </p>

{% endblock content %}

app/templates/book.html
{% extends 'layout.html' %}
{% block content %}
    {% for booking in bookings %}
        {{ user.bookings }}
    {% endfor %}

{% endblock %}

app/templates/home.html
<!-- Contributors: Kowther (pagination), Ariel (search form), Aure (Posts) -->
{% extends 'layout.html' %}

{% block content %}

    <div class="filter-all">
        <p class="filter" style="font-family: Montserrat, sans-serif;  ">Filter your search!</p>
        <form class="form-inline ml-auto" action="search" method="post">
            <div class="filter">
                <input class="form-control" type="search" name="location" placeholder="Enter location">
            </div>
            <div class="filter">
                <select class="form-control" name="size" id="size">
                    <option value="" selected>Select a size</option>
                    <option value="Extra Small">XS</option>
                    <option value="Small">S</option>
                    <option value="Medium">M</option>
                    <option value="Medium Large">ML</option>
                    <option value="Large">L</option>
                    <option value="Extra Large">XL</option>
                </select>
            </div>
            <br>
            <div class="filter">
                <input class="btn btn-success form-control" type="submit" placeholder="submit">
            </div>
        </form>
    </div>

    {# the posts are now paginate items thus posts.items is required #}
    {% for post in posts.items %}
        <div class="post">
            <div class="media content-section">

                <img class="mr-3 article-image post_image"
                     src="{{ url_for('static', filename='post_pictures/' + post.image, width=5000, height =5000) }}">
                <hr width="1" size="500">
                <div class="media-body">
                    {% if current_user.is_authenticated %}
                        <h4 class="media-heading"><a
                                href="{{ url_for('posts.single_post', post_id=post.post_id) }}">{{ post.title }}</a>
                        </h4>
                    {% else %}
                        <h4 class="media-heading"> {{ post.title }}</h4>

                    {% endif %}

                    <p>Posted by <a
                            href="{{ url_for('main.view_profile', userid=post.author.user_id) }}">{{ post.author.username }}</a>
                    </p>
                    <p>{{ post.content }}</p>
                    <p> {{ post.location }}</p>
                    <small> Date posted: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
            </div>
        </div>
        <!-- Modified from: https://github.com/CoreyMSchafer/code_snippets/blob/master/Python/Flask_Blog/09-Pagination/flaskblog/templates/home.html
           Date of Retrieval: [2020/04/10]-->
        <!--this section of code enables the search results to be paginated, it ensures that the button with the page number
        being viewed is filled in (see the different classes btn btn-info mb-4 for when it should be filled in and
        btn btn-outline-info mb-4 for just a button with an outline) finally as the number of pages increase an else statement
        ensures that an ellipsis will break up the page numbers-->
    {% endfor %}
    {% for page_num in posts.iter_pages() %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home_page', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('main.home_page', page=page_num) }}">{{ page_num }}</a>
            {% endif %}

        {% else %}
            ...
        {% endif %}

    {% endfor %}


{% endblock content %}

app/templates/layout.html
<!-- Contributors: Kowther Elmi, Aure Enkaoua
this is the layout page which all pages extend from which includes the main elements
for every page such as the navbar and footer-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- this makes sure it is responsive to different screen sizes-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- link to font -->
    <link href="https://fonts.googleapis.com/css?family=Sriracha&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Mr+Dafoe"/>
    <!--The link to our stylesheet -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='design.css') }}">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->

    {# the title of the head will change depending on the page we are at. We can do this with an if statement #}
    <link rel="stylesheet" href=" https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {# In each route, we enter the title of that specific page. If there's no title specified,
    it will take the name space4less. #}
    {% if title %}
        <title> {{ title }} </title>
    {% else %}
        <title> {{ space4less }}</title>
    {% endif %}

</head>

<body>
<header>

    <!-- Navbar code modified from: https://codepen.io/jo_Geek/pen/xgbaEr, Date of retrieval: [2020/02/17]-->
    <nav class="nav">
        <!-- allows for clicking the navbar icon when the screen is small-->
        <input type="checkbox" id="nav-check">

        <!-- navbar title on the left -->

        <div class="nav-header">
            <div class="nav-title">
                Space<span
                    style='color: red; font-family: "Mr Dafoe"; font-size: 50px; font-style: normal; font-variant: normal; font-weight: 700; line-height: 26.4px; '> 4 </span>
                Less
            </div>
        </div>


        <!-- design of the nav-bar icon when the screen is small-->
        <div class="nav-btn menu-small">
            <label for="nav-check">
                <span></span>
                <span></span>
                <span></span>
            </label>
        </div>

        <!-- navbar content on the right -->
        <div class="nav-links">
            {# the navbar links will change depending on who is logged in/if you are logged in #}
            <a href="{{ url_for('main.home_page') }}"> Home/Browse</a>
            {% if current_user.is_authenticated %}
                {% if current_user.roles == 'property_owner' %}
                    <a href="{{ url_for('posts.post') }}" target="_blank"> Post </a>
                {% endif %}
                <a href="{{ url_for('auth.logout') }}">Logout</a>
                <a href="{{ url_for('user.profile') }}">My profile</a>


            {% else %}
                <a href="{{ url_for('auth.signup') }}">Signup</a>
                <a href="{{ url_for('auth.login') }}">Login </a>
                <a href="{{ url_for('main.about_me') }}">About Us </a>
            {% endif %}

        </div>

    </nav>
</header>
<hr>

<div class="main-body">
    {# in order to display the flash messages, we will put it at the top of each page so that you will see it no matter what page you are on #}
    {% with messages=get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock content %}
</div>

<!--Modified from: https://codepen.io/slstudios/pen/rVYbqM Date of retrieval [2020/04/01] -->
<footer class="footer-distributed">

    <div class="footer-left">

        <span><img class="logo" src="../static/logo-footer.png" alt=" "></span>

        <p class="footer-links">
            <a href="{{ url_for('main.home_page') }}">Home</a>
            ·
            <a href="{{ url_for('main.about_me') }}">About</a>
            ·
            <a href="{{ url_for('main.faq') }}">FAQ</a>
        </p>

        <p class="footer-company-name">Space4Less © 2020</p>

        <div class="footer-icons">

            <a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com"><i class="fa fa-twitter"></i></a>
            <a href="https://www.linkedin.com"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com"><i class="fa fa-github"></i></a>

        </div>

    </div>

    <div class="footer-right">

        <p>Contact Us</p>
        <br>
        <p>spaceforlessproject@gmail.com</p>
    </div>

</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>
</html>

app/templates/payment.html
{# Description: Payment process withs stripe. #}
{# Contributors: Aure Enkaoua #}

{% extends 'layout.html' %}
{% block content %}
    {# Specifying how much the person needs to pay #}
    <h1>you are making a payment of £ {{ invoice.price }}</h1>
    <div class="align_center">
        {# Form from one of the stripe already made forms, but different data used.
    The data currency is in GBP, and the data-amunt needs to be multiplied by 100 as it is in
    cents, but the form was specified in pounds.#}
        <form action="{{ url_for('booking.pay', bookid=invoice.book_id) }}" method="POST">
            <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="{{ pub_key }}"
                    data-amount="{{ invoice.price *100 }}"
                    data-name="Space4less"
                    data-description="renting a space"
                    data-image="/static/logo.jpg"
                    data-locale="auto"
                    data-currency="GBP">
            </script>
        </form>
    </div>

{% endblock content %}

app/templates/search.html
<!-- Contributors: Kowther (pagination), Ariel (results display) -->
{% extends 'layout.html' %}

{% block content %}

    <div class="filter-all">
        <p class="filter" style="font-family: Montserrat, sans-serif;  ">Filter your search!</p>
        <form class="form-inline ml-auto" action="search" method="post">
            <div class="filter">
                <input class="form-control" type="search" name="location" placeholder="Enter location">
            </div>
            <div class="filter">
                <select class="form-control" name="size" id="size">
                    <option value="" selected>Select a size</option>
                    <option value="Extra Small">XS</option>
                    <option value="Small">S</option>
                    <option value="Medium">M</option>
                    <option value="Medium Large">ML</option>
                    <option value="Large">L</option>
                    <option value="Extra Large">XL</option>
                </select>
            </div>
            <div class="filter">
                <input class="btn btn-success form-control" type="submit" placeholder="submit">
            </div>
            <div class="filter">
                <p style="font-family: Montserrat, sans-serif">Showing results for {{ size_for_display }} sized spaces
                    in {{ location_for_display }}</p>
            </div>
        </form>
    </div>


    {# the results are now paginate items thus results.items is required #}
    {% for result in results.items %}
        <div class="post">
            <div class="media content-section">

                <img class="mr-3 article-image post_image"
                     src="{{ url_for('static', filename='post_pictures/' + result.image, width=5000, height =5000) }}">
                <hr width="1" size="500">
                <div class="media-body">
                    {% if current_user.is_authenticated %}
                        <h4 class="media-heading"><a
                                href="{{ url_for('posts.single_post', post_id=result.post_id) }}">{{ result.title }}</a>
                        </h4>
                    {% else %}
                        <h4 class="media-heading"> {{ result.title }}</h4>

                    {% endif %}
                    <p>Posted by <a href="#">{{ result.author.username }}</a></p>
                    <p>{{ result.content }}</p>
                    <small> Date posted: {{ result.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- Modified from: https://github.com/CoreyMSchafer/code_snippets/blob/master/Python/Flask_Blog/09-Pagination/flaskblog/templates/home.html
    Date of Retrieval: [2020/04/10]-->
    <!--this loop of code enables the search results to be paginated, it ensures that the button with the page number
being viewed is filled in (see the different classes btn btn-info mb-4 for when it should be filled in and
btn btn-outline-info mb-4 for just a button with an outline) finally as the number of pages increase an else statement
ensures that an ellipsis will break up the page numbers-->
    {% for page_num in results.iter_pages() %}
        {% if page_num %}
            {% if results.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.search', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('main.search', page=page_num) }}">{{ page_num }}</a>
            {% endif %}

        {% else %}
            ...
        {% endif %}

    {% endfor %}


{% endblock content %}